# ETAPA 1: Construcción (Node.js)
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# --- VARIABLES INYECTADAS DESDE EL TASKFILE ---
ARG VITE_USER_URL
ARG VITE_KEYCLOAK_URL
ARG VITE_CHALLENGES_URL

ENV VITE_USER_URL=$VITE_USER_URL
ENV VITE_KEYCLOAK_URL=$VITE_KEYCLOAK_URL
ENV VITE_CHALLENGES_URL=$VITE_CHALLENGES_URL
# ----------------------------------------------

RUN npm run build

# ETAPA 2: Servidor (Nginx)
FROM nginx:alpine

# Copiamos la configuración ultra-optimizada de Nginx
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Copiamos los archivos construidos al servidor Nginx
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]