# k3s/home-server/keycloak.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: sara
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              'until nc -z -v -w30 postgres-infra 5432; do echo "Waiting for DB..."; sleep 2; done;',
            ]
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.0
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: keycloak-admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: keycloak-password
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://postgres-infra:5432/keycloak"
            - name: KC_DB_USERNAME
              value: "postgres"
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: db-password
            - name: KC_HOSTNAME_URL
              value: "https://auth.saramg.org"
            - name: KC_HOSTNAME_ADMIN_URL
              value: "https://auth.saramg.org"
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "true"
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_PROXY_HEADERS
              value: "xforwarded"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1.5Gi"
              cpu: "1000m"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: sara
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
