# k3s/home-server/service-challenges.yaml

apiVersion: v1
kind: Service
metadata:
  name: service-challenges
  namespace: sara
spec:
  type: ClusterIP
  selector:
    app: service-challenges
  ports:
    - port: 8081
      targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-challenges
  namespace: sara
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-challenges
  template:
    metadata:
      labels:
        app: service-challenges
    spec:
      hostAliases:
        - ip: "100.114.58.117"
          hostnames:
            - "ai-server.taild995dd.ts.net"
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.36
          command:
            [
              "sh",
              "-c",
              'until nc -z -v -w30 postgres-infra 5432; do echo "Waiting for DB..."; sleep 2; done;',
            ]
      containers:
        - name: service-challenges
          image: saramojon/service-challenges:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: gamification-db-url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: gamification-db-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: gamification-db-password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "validate"
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
              value: "50"
            # SEGURIDAD KEYCLOAK
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "https://auth.saramg.org/realms/masorange-realm"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              value: "http://keycloak:8080/realms/masorange-realm/protocol/openid-connect/certs"
            - name: SPRING_DATA_REDIS_HOST
              value: "redis"
            - name: SPRING_DATA_REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: redis-password
            # SLACK
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: slack-bot-token
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: slack-signing-secret
            - name: SLACK_CHANNEL_TEST_ID
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: slack-channel-test-id
            # 2. Comunicación Interna y APIs Externas
            - name: SERVICE_GAMIFICATION_URL
              value: "http://service-gamification:8082"
            - name: SERVICE_USER_URL
              value: "http://service-user:8080"
            - name: OLLAMA_URL
              value: "http://ai-server.taild995dd.ts.net"
            - name: JUDGE0_URL
              value: "http://judge0-server:2358"
            - name: FRONTEND_URL
              value: "https://app.saramg.org"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
