# ==========================================================
# 3. SEGURIDAD (OAUTH2 / KEYCLOAK)
# ==========================================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/masorange-realm