DROP TABLE IF EXISTS challenge_languages;
DROP TABLE IF EXISTS challenge_templates;

CREATE TABLE duels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,          
    retador_id VARCHAR(255) NOT NULL,
    oponente_id VARCHAR(255) NOT NULL,
    challenge_id BIGINT NOT NULL,
    canal_slack_id VARCHAR(50) NOT NULL,
    status VARCHAR(20) NOT NULL, -- PENDING, ACTIVE, FINISHED, REJECTED
    winner_id VARCHAR(255), -- NULL hasta que se complete el duelo
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);