CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50),
    email VARCHAR(100),
    nombre VARCHAR(100)
);

-- (Opcional) Insertamos un usuario de prueba para que puedas loguearte ya
-- La pass 'admin' suele ser hash, pero para probar la conexión vale
INSERT INTO users (username, password, role, email, nombre) 
VALUES ('admin', 'admin', 'ADMIN', 'admin@masorange.es', 'Administrador');