ALTER TABLE users DROP COLUMN IF EXISTS password;

ALTER TABLE users ADD COLUMN IF NOT EXISTS keycloak_id VARCHAR(255) UNIQUE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS score INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_language VARCHAR(50) DEFAULT 'Java';

ALTER TABLE users ALTER COLUMN role SET DEFAULT 'user';